### ISSUE TITLE
去重小工具

### ISSUE THREAD

**Issue by etigerstudio** [globalcitizen/2019-wuhan-coronavirus-data#11]
自闭了几次，算是搞了个能用的自动去重的命令行工具。各种平台有预先编译好的版本，[下载](https://github.com/etigerstudio/2019-ncov-data-util/releases)之后每次需要去重时运行：

```
./nutil gdedupe dxy/data
```

就可以对指定目录（dxy）的全部记录都扫描一遍，去掉包括对应区域数字和注释完全一致（数据行的顺序无关，这点与 md5 不同）的重复记录的相关文件。

如果需要每次拉取数据后立即去重，则推荐执行：

```
./nutil gdedupe -n 2 dxy/data
```

这样的好处是只读取文件名上时间最靠后的两个记录，节省资源。

如果有发现什么毛病，欢迎提出来，我再改。

**Comment by globalcitizen** [comment]
OK 但是工具在哪？

**Comment by etigerstudio** [comment]
工具在这里~ https://github.com/etigerstudio/2019-ncov-data-util/releases （其实就是上一条评论里`下载`二字的链接，确实不够明显）。

另外说一句，这个工具因为各个平台架构的二进制执行文件不通用，所以就不用放到 git仓库 里做版本控制了。

**Comment by globalcitizen** [comment]
抱歉，如果我没有花足够的时间来理解您的消息，这对我来说只是一个业余爱好项目，我通过翻译员传达了您的消息。

这是我在20行perl中想要的实用程序：https://github.com/globalcitizen/2019-wuhan-coronavirus-data/blob/master/data-sources/dxy/data/remove-dupes
