### ISSUE TITLE
Some ~20200126 DXY records have incorrect total string

### ISSUE THREAD

**Issue by cryptid11** [globalcitizen/2019-wuhan-coronavirus-data#13]
https://github.com/globalcitizen/2019-wuhan-coronavirus-data/blob/1f4b4966b25863949a6611cb2f7b2143905214bf/data-sources/dxy/data/20200126-125300-dxy-2019ncov-data.csv#L37

**Comment by globalcitizen** [comment]
Yes, there's a few CSVs with that issue. It was a temporary issue related to use of the wrong string concatenation vs. addition operator in the CSV conversion script. Can't promise to resolve it soon, for now I suggest totalling the other records instead.

**Comment by cryptid11** [comment]
"Can't promise to resolve it soon"? is it so difficult? I can help if you explain the problem, maybe get some help with this https://github.com/BlankerL/DXY-2019-nCoV-Crawler

**Comment by globalcitizen** [comment]
I don't appreciate your rudeness.

**Comment by cryptid11** [comment]
nobody appreciate rudness, but it can be in actions or in tone, and the
first is way worst.

**Comment by ihello-world** [comment]
I have tried to synthesize data from WHO to create a coronavirus timeline from the beginning until today. I want to share for everyone to follow [link](https://www.youtube.com/watch?v=zQadr3b_kmo&list=PLQYKsWZ3Q7jz2MfR-GAb9j65cgzHlpJbS)

I am very happy to hear from you. Please support me :)
