### ISSUE TITLE
Truncated Files List

### ISSUE THREAD

**Issue by ceweiss** [globalcitizen/2019-wuhan-coronavirus-data#14]
Hi,

Given that the dxy data list gets truncated to 1000 files, any chance you can include the zip file with all data in those 1000 files? Or set the upload to show the most recent data, rather than the oldest data?

Thanks.

**Comment by globalcitizen** [comment]
I do not understand what you mean by "truncated".

Can you explain:
- What are you trying to achieve
- Which platform are you on
- What did you do exactly
- What did you expect to happen
- What actually happened

**Comment by ceweiss** [comment]
![Capture](https://user-images.githubusercontent.com/23327171/74026410-0e316500-499e-11ea-8d03-ecc9514d704b.PNG)

The dxy data folder is limited to 1000 files. So downloading the package does not include the most recent data that your tool has collected.

**Comment by globalcitizen** [comment]
You do not understand enough about files and git repositories for me to assist you. I suggest you learn to use either the command line `git` client or install the Github desktop app to help you get the files. If your operating system doesn't support 1000 files in a directory, just download the ones you want.
