### ISSUE TITLE
WHO Situation Report Data

### ISSUE THREAD

**Issue by eebrown** [globalcitizen/2019-wuhan-coronavirus-data#17]
Regarding your TODO to get the WHO Situation Report Data, I have been transcribing it to a .csv for a simple R package. It's freely available here: https://github.com/eebrown/data2019nCoV

**Comment by globalcitizen** [comment]
Wow that looks like a lot of work. Thanks for the heads up, it's a great resource.

Someone should rewrite the BNO international renderer with that data. However, it will require a manual translation layer from the nonstandard toponym codes you have as column titles in the CSV. It won't be me as I am out of time for this project and I also consider the international spread less interesting than the domestic spread, and WHO reports are only daily (less precision).

**Comment by larsonreever** [comment]
this will help us a long way as we are coming up with a community based solution to track coronavirus near you - initiative named [Corona Warriors](https://coronawarriors.com/), it will be an innovative step ahead to help the spread. Github has lots of good resources which we can levarage. Contributions & partnerships are welcome.

**Comment by Evelyn-coral** [comment]
I think it's UNRIGHT to use the sloppy name "2019-wuhan-coronavirus-data".
Where the virus comes from is a difficult and complex scientific issue. Please don't regard this issue with geographical discrimination. 
Chinese people, especially those in Wuhan, have made and are still making huge sacrifice to fight against the virus. 
By the way, the virus has its name "2019nCoV". Although it's a strange name, it's better.
