### ISSUE TITLE
How to get build to run?

### ISSUE THREAD

**Issue by ceweiss** [globalcitizen/2019-wuhan-coronavirus-data#6]
Hi there! Great work with your package.

I've unfortunately never worked with command line before, and cannot get the build function to work. I've downloaded the package and put it in my C drive. Then navigated to it in command prompt and tried this:

C:\2019-wuhan-coronavirus-data-master>build china
'build' is not recognized as an internal or external command,
operable program or batch file.

as well as this:

C:\2019-wuhan-coronavirus-data-master>./build china
'.' is not recognized as an internal or external command,
operable program or batch file.

How can I get this to run?

Sorry for the complete noob question.

**Comment by globalcitizen** [comment]
It requires a unix-like OS, I will write this in the requirements.
